### PR TITLE
Update Product Scope #37

### PR DESCRIPTION
**Pull request by cookiedan42**

### CODE REVIEW

**Review by Jiwei99 — COMMENTED** [review]
The user profile and value proposition is not really the same as in the docs tho, also is it too focused on birthday parties?

**Comment by cookiedan42** [comment]
> 
> 
> The user profile and value proposition is not really the same as in the docs tho, also is it too focused on birthday parties?

Purpose of writing this way is to focus the functionality together in a birthday related direction. Tags can be used for other purposes too, but one immediate relevance to birthdays is for party information

Also, where in the docs are you referring to? I might have missed it while writing this segment

**Comment by Jiwei99** [comment]
I gets but I'm not sure if it might make it sound like a sound like a solely birthday based application. Maybe can add in some more general user profiles?

> Also, where in the docs are you referring to? I might have missed it while writing this segment

It's in the google doc, at the very beginning.

**Comment by cookiedan42** [comment]
Ah yes I see your point, added the general profiles ahead of the more specific party profiles

**Review by Justinhoejj — APPROVED** [review]
Good to merge

**Review by yucheng11122017 — APPROVED** [review]
LGTM

**Pull request merged**
