### PR TITLE
Fix typesetting of documentation

### PR DESCRIPTION
**Pull request by cookiedan42**
For PDF printing

PR version of docs currently hosted at https://cookiedan42.github.io/tp/
Contributes to #214 
Contributes to #215

### CODE REVIEW

**Comment by cookiedan42** [comment]
First Pass on UG typesetting complete

**Comment by cookiedan42** [comment]
First pass on DG typesetting for PDF done
- sections broken up logically

**Review by Jiwei99 — APPROVED** [review]
LGTM

**Review by yucheng11122017 — APPROVED** [review]
LGTM!

**Pull request merged**
