### PR TITLE
Docs typesetting

### LINKED ISSUE #215: Typesetting for Developer Guide
Ensure content is OK
Ensure PDF conversion is OK

### PR DESCRIPTION
**Pull request by cookiedan42**
Closes #215

### CODE REVIEW

**Review by leezhixuan — APPROVED** [review]
one last LGTM

**Review by yucheng11122017 — APPROVED** [review]
LGTM

**Review by Justinhoejj — APPROVED** [review]
LGTM

**Review by Jiwei99 — APPROVED** [review]
LGTM

**Pull request merged**
