### PR TITLE
Update AboutUs about me and update Ui MockUp

### LINKED ISSUE #6: UI Mock Up
Add a UI mockup of your intended final product. Note that the image of the UI should be docs/images/Ui.png so that it can be downloaded by our scripts. Limit the file to contain one screenshot/mockup only and ensure the new image is roughly the same height x width proportions as the original one.

If done correctly UI mock up will appear in [project list page](https://nus-cs2103-ay2122s1.github.io/website/admin/teamList.html).

### PR DESCRIPTION
**Pull request by yucheng11122017**
Contributes to #5 
Closes #6

### CODE REVIEW

**Comment by Justinhoejj** [comment]
LGTM although, I think Update UI should be renamed to Update UI Mock Up for more clarity.

**Review by Justinhoejj — CHANGES_REQUESTED** [review]
LGTM although, I think Update UI should be renamed to Update UI Mock Up for more clarity.

**Review by cookiedan42 — APPROVED** [review]
LGTM

**Review by Justinhoejj — APPROVED** [review]
LGTM

**Pull request merged**
